import type { Metadata } from "next";
import { Unbounded, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { gallerys } from "@/app/data";
import Image from "next/image";
import logo from "@/public/logo.svg";
import menu from "@/public/menu.svg";
import {
  ChevronDown,
  Facebook,
  Linkedin,
  Search,
  Twitter,
} from "lucide-react";
import { cn } from "@/lib/utils";
import ThemeToggle from "./theme-toggle";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const inter = Unbounded({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bizify Digital Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"   suppressHydrationWarning
 className={cn("font-mono", jetbrainsMono.variable)}>
      <body className={`${inter.className} antialiased`} >
<header className="bg-[#FBFBFB] dark:text-[#282626] flex items-center justify-between px-10 py-4">

  <Image src={logo} alt="Bizify Logo" width={150} height={50} />

  <nav>
    <ul className="flex items-center gap-6">
      <li className="flex items-center gap-1 cursor-pointer">
        <a href="#">Home</a>
        <ChevronDown size={16} />
      </li>

      <li>
        <a href="#">About us</a>
      </li>

      <li className="flex items-center gap-1 cursor-pointer">
        <a href="#">Pages</a>
        <ChevronDown size={16} />
      </li>

      <li className="flex items-center gap-1 cursor-pointer">
        <a href="#">Blog</a>
        <ChevronDown size={16} />
      </li>

      <li>
        <a href="#">Contact</a>
      </li>
    </ul>
  </nav>

  <div className="flex items-center gap-4">
    <ThemeToggle />
    <Search className="cursor-pointer" />
    <Image src={menu} alt="menu icon" width={24} className="cursor-pointer" />
  </div>

</header>     <ThemeProvider attribute='class' enableSystem defaultTheme="system">{children}</ThemeProvider>   

<footer className="bg-[#F4F5F6]  px-16 py-14 grid grid-cols-4 gap-12">

  <div className="flex flex-col gap-6">
    <Image src={logo} alt="logo" />

    <p className="text-gray-600">
      Monotonectally synergize granular top visualize strategic
      infomediaries after task state of the art infrastructures.
    </p>

    <div className="flex gap-4">
      <div className="bg-white p-2 rounded hover:bg-[#84A17D] dark:hover:bg-black dark:hover:text-white dark:bg-[#84A17D] cursor-pointer">
        <Facebook />
      </div>

      <div className="bg-white p-2 rounded hover:bg-[#84A17D] dark:hover:bg-black dark:hover:text-white dark:bg-[#84A17D] cursor-pointer">
        <Twitter />
      </div>

      <div className="bg-white p-2 rounded hover:bg-[#84A17D] dark:hover:bg-black dark:hover:text-white dark:bg-[#84A17D] cursor-pointer">
        <Linkedin />
      </div>
    </div>
  </div>

  <div>
    <h3 className="font-semibold mb-4 dark:text-[#172426]">Quick Links</h3>

    <ul className="flex flex-col gap-3 text-gray-600">
      <li><a href="#">Home</a></li>
      <li><a href="#">About us</a></li>
      <li><a href="#">Pages</a></li>
      <li><a href="#">Blog</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>

  <div>
    <h3 className="font-semibold mb-4 dark:text-[#172426]">Useful Links</h3>

    <ul className="flex flex-col gap-3 text-gray-600">
      <li><a href="#">Company</a></li>
      <li><a href="#">Career</a></li>
      <li><a href="#">Our Blog</a></li>
      <li><a href="#">Press Media</a></li>
      <li><a href="#">Privacy Policy</a></li>
    </ul>
  </div>

  <div className="grid grid-cols-3 gap-4">
    {gallerys.map((gallery, index) => (
      <Image
        key={index}
        src={gallery}
        alt="gallery"
        width={90}
        height={90}
        className="rounded"
      />
    ))}
  </div>

</footer> 
      </body>
   </html>
  );
}
